/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PlaylistTrack } from "./PlaylistTrack";
import { PlaylistTrackCountArgs } from "./PlaylistTrackCountArgs";
import { PlaylistTrackFindManyArgs } from "./PlaylistTrackFindManyArgs";
import { PlaylistTrackFindUniqueArgs } from "./PlaylistTrackFindUniqueArgs";
import { CreatePlaylistTrackArgs } from "./CreatePlaylistTrackArgs";
import { UpdatePlaylistTrackArgs } from "./UpdatePlaylistTrackArgs";
import { DeletePlaylistTrackArgs } from "./DeletePlaylistTrackArgs";
import { Playlist } from "../../playlist/base/Playlist";
import { Track } from "../../track/base/Track";
import { PlaylistTrackService } from "../playlistTrack.service";
@graphql.Resolver(() => PlaylistTrack)
export class PlaylistTrackResolverBase {
  constructor(protected readonly service: PlaylistTrackService) {}

  async _playlistTracksMeta(
    @graphql.Args() args: PlaylistTrackCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PlaylistTrack])
  async playlistTracks(
    @graphql.Args() args: PlaylistTrackFindManyArgs
  ): Promise<PlaylistTrack[]> {
    return this.service.playlistTracks(args);
  }

  @graphql.Query(() => PlaylistTrack, { nullable: true })
  async playlistTrack(
    @graphql.Args() args: PlaylistTrackFindUniqueArgs
  ): Promise<PlaylistTrack | null> {
    const result = await this.service.playlistTrack(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PlaylistTrack)
  async createPlaylistTrack(
    @graphql.Args() args: CreatePlaylistTrackArgs
  ): Promise<PlaylistTrack> {
    return await this.service.createPlaylistTrack({
      ...args,
      data: {
        ...args.data,

        playlist: args.data.playlist
          ? {
              connect: args.data.playlist,
            }
          : undefined,

        track: args.data.track
          ? {
              connect: args.data.track,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => PlaylistTrack)
  async updatePlaylistTrack(
    @graphql.Args() args: UpdatePlaylistTrackArgs
  ): Promise<PlaylistTrack | null> {
    try {
      return await this.service.updatePlaylistTrack({
        ...args,
        data: {
          ...args.data,

          playlist: args.data.playlist
            ? {
                connect: args.data.playlist,
              }
            : undefined,

          track: args.data.track
            ? {
                connect: args.data.track,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PlaylistTrack)
  async deletePlaylistTrack(
    @graphql.Args() args: DeletePlaylistTrackArgs
  ): Promise<PlaylistTrack | null> {
    try {
      return await this.service.deletePlaylistTrack(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Playlist, {
    nullable: true,
    name: "playlist",
  })
  async getPlaylist(
    @graphql.Parent() parent: PlaylistTrack
  ): Promise<Playlist | null> {
    const result = await this.service.getPlaylist(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Track, {
    nullable: true,
    name: "track",
  })
  async getTrack(
    @graphql.Parent() parent: PlaylistTrack
  ): Promise<Track | null> {
    const result = await this.service.getTrack(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
